# Generated by Django 3.2.3 on 2021-05-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20210528_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
